rule_files:
  - "recording_rules.yml" 

scrape_configs:
  - job_name: 'pushgateway'
    scrape_interval: 15s
    honor_labels: true # Importante to keep labels (like function_name)
    static_configs:
      - targets: ['pushgateway:9091']