global:
  scrape_interval: 15s
  evaluation_interval: 15s

# rule_files:
#   - "recording_rules.yml" 

scrape_configs:
  - job_name: 'pushgateway'
    honor_labels: true # Important to keep labels (like function_name)
    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'stackdriver-exporter'
    static_configs:
      - targets: ['stackdriver-exporter:9255']